### ISSUE TITLE
different intnet for buy than other markets

### ISSUE THREAD

**Issue by sajadabasi** [cafebazaar/TrivialDrive#12]
hello,
why your intent for buy is different from others markets
```
        Intent serviceIntent = new Intent("ir.cafebazaar.pardakht.InAppBillingService.BIND");
        serviceIntent.setPackage("com.farsitel.bazaar");
```
all other markets is same but for yours is `ir.cafebazaar.pardakht` and `com.farsitel.bazaar` what is the need to do this?

**Comment by ebraminio** [comment]
Bazar's package name still is "com.farsitel.bazaar" and that perhaps predates the registration time of a dedicated domain for cafebazaar website even, but later developments of Bazaar codebase happened on "ir.cafebazaar.*" due to the fact it is the main domain Bazaar used after gaining an initial success between another ideas farsitel had.
