### ISSUE TITLE
Not allowed to bind to service Intent

### ISSUE THREAD

**Issue by MBehtemam** [cafebazaar/TrivialDrive#5]
i try to test IAP of cafebazaar before publishing my app. so i upload my app and create a product and import helper class and libs and set everythings that need.but when i start my activity that has IAP codes is force stop the app and the log say : 

    Not allowed to bind to service Intent { act=ir.cafebazaar.pardakht.InAppBillingService.BIND pkg=com.farsitel.bazaar }

i search and find it's need permission on manifest but i set this permission : 

         <uses-permission android:name="com.farsitel.bazaar.permission.PAY_THROUGH_BAZAAR" />

but the error still happen on genymotion and real device.

**Comment by hirbodk** [comment]
@MBehtemam please specify your target SDK version and Android version of the device you're using.

**Comment by MBehtemam** [comment]
I successfully run the payment and you right the problem ins SDK version. i try to use last Android SDK and version (Android Version 6 and API ) and this version has different permission manager so i thingk `<uses-permission ...........` doesn't work on Android 6 but it's work correctly on android 4.2.2 and API 17 on genymotion.

**Comment by hirbodk** [comment]
Currently with a API 23 app on Android 6 you need to turn on the Payment Through Bazaar permission manually in Settings. In the next version this issue will be fixed and there will be no need to do anything with the permissions manually.
Thank you

**Comment by mhm90** [comment]
Hi, Same here on some devices! We have published our app recently and since then we are getting some crash report: I am using a bug report tool that reports all happened crashes to my server, here is the stacktrace:
`java.lang.SecurityException Not allowed to bind to service Intent { act=ir.cafebazaar.pardakht.InAppBillingService.BIND pkg=com.farsitel.bazaar }`
`    ContextImpl.java:1508 android.app.ContextImpl.bindService`
`    ContextImpl.java:1479 android.app.ContextImpl.bindService`
`    ContextWrapper.java:473 android.content.ContextWrapper.bindService`
`    IabHelper.java:269 util.IabHelper.startSetup`
`    ...`

My build target is API 23

Here is devices specifications:

`Sony C2305 : Android 4.4.2`
`Samsung S-A310F : Android 5.1.1`
`HUAWEI Y550-L02 : Android 4.4.4`
`Samsung SM-N910G : Android 6.0.1`
`Samsung SM-G920F : Android 6.0.1`
`Samsung SM-G900H : Android 6.0.1`

**Comment by choephix** [comment]
@mhm90 hey, did you find a solution to your problem? I'm having the same one.

**Comment by oky2abbas** [comment]
+1
